platformName=Android
## edit the Device Name as per your device Name
deviceName=Device1
# edit the app path
app=/Users/jimmy/Downloads/app-debug.apk
automationName=UiAutomator2
appPackage=com.yasinkacmaz.jetflix.debug
appActivity=com.yasinkacmaz.jetflix.ui.main.MainActivity
appiumJSPath_Mac=/usr/local/lib/node_modules/appium/build/lib/main.js
#add the path of the js of appium for windows
appiumJSPath_Windows=C:\\Users\\YourUser\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js

