platformName=Android
deviceName=Device1
app=/Users/jimmy/Downloads/app-debug.apk
automationName=UiAutomator2
appPackage=com.yasinkacmaz.jetflix.debug
appActivity=com.yasinkacmaz.jetflix.ui.main.MainActivity
appiumJSPath_Mac=/usr/local/lib/node_modules/appium/build/lib/main.js
appiumJSPath_Windows=C:\\Users\\YourUser\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js

